# instagram (me and my friends)
# moosa.tae
# chotpipsit.nac
# rufflogix
# teamangkorn

f = open("text.txt", "r")

dict = {}
for c in f:
    dict[c] = 1

ret = 0

ls = str("CYSCNRLGUNXOFMCBKLBWAWAUC
VNXWHMEXDZJXZSTUYCGDPBNZZ
RQARFLEBQMYTWAZBGUXYRXGMU
HAHZFFAKXJALYEPRLSNJBXDAL
UUAMOWHHYSPXHFTUUCIDFCAPV
ACKIWDGAUAEVHEOPPIPZGSHOA
VLCGJWYSZLUSKFMFKLPYTHONH
GIEBKGIKLTYZZADKLIXRRIRHC
XQJFLIVETSIQPYGCISGUDWWHY
REPTCHJLYZEUTYUTKPTBSWLKS
NKDEIMCLWEMMHVKECDOYIFEZC
JBMFNZILLJLJXZLYWIIGDWSCH
IWPVRBHQFCJHULHFSUAIHBFWE
DENAOCKJITXMONGLASSEMBLYM
MWHYUKXTLHXUDXZACRFOSYMJE
MEHIYHAEDHZXHUNUVLBYZYLCN
WDAZEZCZAUNTVNQDGPFTLDPFD
YOVDDHENCFPGWDTGEUCSHNUHB
DYHJKNXVCFTYPESCRIPTTTAOL
WMJRNDWFQKHJAVASCRIPTAQCC
CLOJURERXUKYOOFTKZWSJOPAW
EKDIPLLAJPJULIARKBUYPHIMQ
YWBCOOQSXIUENXLUYATDXATLZ
YPPLHSPJWEDSVELSSHESZQWKY
UUMFDWTSMTIMNZTTVMNHDCGNQ)







print(ret)